[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps = 
    seeed-studio/Grove-3-Axis-Digital-Accelerometer-2g-to-16g-LIS3DHTR@^1.2.4
    thewknd/VEML6040@^0.3.2
    seeed-studio/Grove Temperature And Humidity Sensor@^2.0.2
