[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200

; PS2X_lib 需要手动放到项目 lib/PS2X_lib/ 目录下
; 库文件来源：.codebuddy/skills/future-tech-box-programmer/references/libraries/PS2X_lib/
